#!/bin/bash 

                         __________
#                      .~#########%%;~.        By Source ABUWSAM
#                     /############%%;`\      Dev : @ALFGEHI07
#                   /######/~\/~\%%;,;,\    Channel : @abuwsamhak
#                  |#######\    /;;;;.,.|   Bot : @abuwsamksa_bot
#                  |#########\/%;;;;;.,.|
#          XX       |##/~~\####%;;;/~~\;,|       XX
#        XX..X      |#|  o  \##%;/  o  |.|      X..XX
#      XX.....X     |##\____/##%;\____/.,|     X.....XX
#XXXXX.....XX      \#########/\;;;;;;,, /      XX.....XXXXX
#X |......XX%,.@      \######/%;\;;;;, /      @#%,XX......| X
#X |.....X  @#%,.@     |######%%;;;;,.|     @#%,.@  X.....| X
#X  \...X     @#%,.@   |# # # % ; ; ;,|   @#%,.@     X.../  X
#X# \.X        @#%,.@                  @#%,.@        X./  #
#  ##  X          @#%,.@              @#%,.@          X   #
#, "# #X            @#%,.@          @#%,.@            X ##
#   `###X             @#%,.@      @#%,.@             ####'
#  . ' ###              @#%.,@  @#%,.@              ###`"
#    . ";"                @#%.@#%,.@                ;"` ' .
#      '                    @#%,.@                   ,.
#      ` ,                @#%,.@  @@                `
#                          @@@  @@@  

#---------------------------------------------------------------------
cd $(cd $(dirname $0); pwd)
RED='\033[0;31m'
SMAY='\033[0;36m' 
GREEN='\033[0;32m'
Yellow='\033[0;33m'
LSAMAY='\033[01;49m'
WHITB='\033[01;90m'
WHITEC='\033[01;91m'
CNIL='\033[0m'
Version=`lsb_release -rs | cut -f1 -d"."`


if [ ! -f "./TG" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Not Dwonload TG .
¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source VEER${CNIL} . \n
\n\n"
chmod +x ./ins
./ins
exit;
fi


if [ ! -f "./inc/Token.txt" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Token Bot Not Found .
¦ NOW I Run File ${SMAY}./RUN.lua${WHITB} To Enter Data For You Bot${CNIL}. \n
\n\n"
lua ./inc/Run.lua
exit;
else
TOKEN=`cat ./inc/Token.txt`
BOTID=`echo $TOKEN | cut -f1 -d":"`
Sudo=$(redis-cli get ${BOTID}:SUDO_ID:)
if [[ $Sudo == "" ]]; then
rm -fr ./inc/Token.txt
lua ./inc/Run.lua
exit;
fi
fi

chmod +x ./TG  

if [ "$1" == "R" ]; then
while true; do
sleep 1s
sudo rm -fr ~/.telegram-cli
./TG -s ./inc/Run.lua --bot=$TOKEN
done
else 
BOTIDS=`echo $TOKEN | cut -f1 -d":"`
if ! screen -list | grep -q "veer_$BOTIDS"; then
screen -S veer_$BOTIDS ./run R
else
screen -X -S veer_$BOTIDS quit
screen -S veer_$BOTIDS ./run R
fi
fi
